const { SlashCommandBuilder, EmbedBuilder, PermissionFlagsBits } = require('discord.js');
const config = require('../../config.json');
const PermissionManager = require('../../utils/permissions');
const db = require('../../utils/database');

module.exports = {
    data: new SlashCommandBuilder()
        .setName('generatepremiumcode')
        .setDescription('Generate a premium code')
        .addIntegerOption(option =>
            option.setName('amount')
                .setDescription('Number of codes to generate (max 5)')
                .setMinValue(1)
                .setMaxValue(5))
        .addStringOption(option =>
            option.setName('note')
                .setDescription('Add a note to the generated codes'))
        .setDefaultMemberPermissions(PermissionFlagsBits.Administrator),

    async execute(interaction) {
        await interaction.deferReply({ ephemeral: true });

        try {
            // Check if user has permission to use this command
            if (!await PermissionManager.isAdmin(interaction.member)) {
                const errorEmbed = new EmbedBuilder()
                    .setColor(config.embedColors.error)
                    .setTitle('❌ Permission Denied')
                    .setDescription('You do not have permission to use this command.')
                    .setFooter({ text: `Requested by ${interaction.user.tag}` })
                    .setTimestamp();

                return await interaction.editReply({ embeds: [errorEmbed] });
            }

            const amount = interaction.options.getInteger('amount') || 1;
            const note = interaction.options.getString('note') || 'No note provided';

            // Generate codes
            const generatedCodes = [];
            for (let i = 0; i < amount; i++) {
                const code = db.generatePremiumCode(interaction.user.id);
                generatedCodes.push(code);
            }

            // Create success embed
            const successEmbed = new EmbedBuilder()
                .setColor(config.embedColors.success)
                .setTitle('✨ Premium Codes Generated')
                .setDescription('Here are your generated premium codes:')
                .addFields(
                    {
                        name: '🎫 Codes',
                        value: generatedCodes.map(code => `\`${code}\``).join('\n'),
                        inline: false
                    },
                    {
                        name: '📝 Note',
                        value: note,
                        inline: false
                    },
                    {
                        name: '⚠️ Important',
                        value: 'Keep these codes safe! They can only be used once.',
                        inline: false
                    }
                )
                .setFooter({ text: `Generated by ${interaction.user.tag}` })
                .setTimestamp();

            await interaction.editReply({ embeds: [successEmbed] });

            // Notify bot owner
            try {
                const ownerUser = await interaction.client.users.fetch(process.env.OWNER_ID);
                const ownerEmbed = new EmbedBuilder()
                    .setColor(config.embedColors.primary)
                    .setTitle('🎫 New Premium Codes Generated')
                    .addFields(
                        {
                            name: 'Generated By',
                            value: `${interaction.user.tag} (${interaction.user.id})`,
                            inline: true
                        },
                        {
                            name: 'Server',
                            value: interaction.guild.name,
                            inline: true
                        },
                        {
                            name: 'Amount',
                            value: amount.toString(),
                            inline: true
                        },
                        {
                            name: '🎫 Codes',
                            value: generatedCodes.map(code => `\`${code}\``).join('\n'),
                            inline: false
                        },
                        {
                            name: '📝 Note',
                            value: note,
                            inline: false
                        }
                    )
                    .setTimestamp();

                await ownerUser.send({ embeds: [ownerEmbed] });
            } catch (error) {
                console.log('Could not send notification to owner:', error);
            }

            // Log to a specific channel if configured
            try {
                const logChannel = interaction.guild.channels.cache.find(
                    channel => channel.name === 'premium-logs'
                );

                if (logChannel) {
                    const logEmbed = new EmbedBuilder()
                        .setColor(config.embedColors.primary)
                        .setTitle('🎫 Premium Codes Generated')
                        .addFields(
                            {
                                name: 'Generated By',
                                value: interaction.user.toString(),
                                inline: true
                            },
                            {
                                name: 'Amount',
                                value: amount.toString(),
                                inline: true
                            },
                            {
                                name: '📝 Note',
                                value: note,
                                inline: false
                            }
                        )
                        .setFooter({ text: 'Premium code generation log' })
                        .setTimestamp();

                    await logChannel.send({ embeds: [logEmbed] });
                }
            } catch (error) {
                console.log('Could not log to premium-logs channel:', error);
            }

        } catch (error) {
            console.error('Error in generatepremiumcode command:', error);

            const errorEmbed = new EmbedBuilder()
                .setColor(config.embedColors.error)
                .setTitle('❌ Command Failed')
                .setDescription(`Failed to generate premium codes: ${error.message}`)
                .setFooter({ text: `Requested by ${interaction.user.tag}` })
                .setTimestamp();

            await interaction.editReply({ embeds: [errorEmbed] });
        }
    },
};